### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by H-CODE6** [zzzqzhou/RAM-DSIR#1]
Hello, the author. After checking your paper, we found that you are still experimenting on the prostate dataset. Can you open the download path of this dataset and run the code on this dataset? We look forward to your reply.

**Comment by zzzqzhou** [comment]
Hi, thanks for your interest in our work. I have updated the download link of the pre-processed prostate dataset. You can now download it and run the code on this dataset.

**Comment by H-CODE6** [comment]
Thank you for your reply. In the acknowledgement, I saw that you thanked FedDG. In order to better understand your code and your work, I also reproduced it, but it seems that the author has not provided the code that converts the file to npy, and the open running process is not very clear. If you see that you have successfully run it, can you tell me the specific running steps, and look forward to your reply.
