### ISSUE TITLE
prostate dataset

### ISSUE THREAD

**Issue by H-CODE6** [zzzqzhou/RAM-DSIR#2]
Hello, the author. After downloading your public prostate dataset, it is found that it includes Domain1-Domain6, 'ISBI' and 'ISBI_ 1.5 ',' I2CVB ',' UCL ',' BIDMC ',' HK 'folders. After testing, I found that Domain1-Domain6 folders were used in training, but only' ISBI 'and' ISBI 'could be used in testing_ 1.5 ',' I2CVB ',' UCL ',' BIDMC ',' HK 'folders, but I am not clear about the Domain1-Domain6 folder and the' ISBI ',' ISBI_ Please inform us of the correspondence between the folders 1.5 ',' I2CVB ',' UCL ',' BIDMC 'and' HK 'and look forward to your reply.

**Comment by zzzqzhou** [comment]
Hi. Thanks for your interest in our work. We have a test domain list in 'code/test_prostate_volume.py'. The list index is also the domain id. Which means **ISBI** is Domain 1, **ISBI_1.5** is Domain 2, **I2CVB** is Domain 3, **UCL** is Domain 4, **BIDMC** is domain 5 and **HK** is Domain 6.  https://github.com/zzzqzhou/RAM-DSIR/blob/cb4aa2b8a52ebf8b50b6afbd9a122554602161a3/code/test_prostate_volume.py#L167

Images in **ISBI**, **ISBI_1.5**, etc. are all 3D volumes. We preprocessed these images into 2D slices (Domain 1 - 6) for training. When testing, we use 3D volumes.

**Comment by H-CODE6** [comment]
Thank you very much for your reply. Your answer has solved my confusion. If it is convenient, can I open the code for converting 3D to 2D? This code is relatively complete. I look forward to your reply.

**Comment by H-CODE6** [comment]
Opening the prostate data set preprocessing code can deepen our understanding of the overall code, and we look forward to your reply.
