### ISSUE TITLE
training on prostate dataset

### ISSUE THREAD

**Issue by hooxizz** [zzzqzhou/RAM-DSIR#3]
hi, author,

I just want to run the code on prostate dataset and meet some mistakes. I use command as below:

```
cd code
python -W ignore train.py --data_root ../dataset --dataset prostate \
--domain_idxs 1,2,3,4,5 --test_domain_idx 0 \
--rec --is_out_domain --consistency --consistency_type kd \
--save_path ../outdir/prostate/target0 --gpu 0
```

Did I forget something？Looking forward your reply. Thanks in advance.

**Comment by zzzqzhou** [comment]
Could you please provide error logs, thus I can help you.

**Comment by Zerua-bit** [comment]
> 嗨，作者，
> 
> 我只想在前列腺数据集上运行代码并遇到一些错误。我使用的命令如下：
> 
> ```
> cd code
> python -W ignore train.py --data_root ../dataset --dataset prostate \
> --domain_idxs 1,2,3,4,5 --test_domain_idx 0 \
> --rec --is_out_domain --consistency --consistency_type kd \
> --save_path ../outdir/prostate/target0 --gpu 0
> ```
> 
> 我忘记了什么吗？期待你的回复。提前致谢。
I've tried several environments and graphics cards, but I keep encountering CUDA errors.

**Comment by Zerua-bit** [comment]
> 您能否提供错误日志，以便我可以为您提供帮助。

I have tried several environments and graphics cards, but I still encounter CUDA errors. However, the fundus dataset can run smoothly.
