### ISSUE TITLE
nan or inf found in input tensor

### ISSUE THREAD

**Issue by minkkkey** [zzzqzhou/RAM-DSIR#4]
This problem occurred while training the prostate dataset. How to solve it? Looking forward your reply. Thanks in advance.
i use pytorch==1.8

**Comment by zzzqzhou** [comment]
Hi, this problem may caused by KD consistency loss. You can use MSE consistency loss when train on the prostate dataset. This will   not make much difference to the result.

**Comment by minkkkey** [comment]
> Hi, this problem may caused by KD consistency loss. You can use MSE consistency loss when train on the prostate dataset. This will not make much difference to the result.

Thank you so much!!!!!!!!!!!!!!!
