### ISSUE TITLE
Environment and Datasets

### ISSUE THREAD

**Issue by XLoveRye** [zzzqzhou/RAM-DSIR#5]
What's the environment of your implementation (including cuda and cudnn)? AND I don't know how to put the datasets into folder properly~ :-(

**Comment by zzzqzhou** [comment]
You can download [Fundus](https://drive.google.com/file/d/1p33nsWQaiZMAgsruDoJLyatoq5XAH-TH/view) and [Prostate](https://drive.google.com/file/d/1-SCjNklFEAq7MlBwcw2ZNR179JqlOubL/view), then unzip and put images in ```./dataset/fundus/``` and ```./dataset/prostate/``` in this repo. There are no specific requirments for environment, you can run the code on the latest PyTorch version.

**Comment by XLoveRye** [comment]
> You can download [Fundus](https://drive.google.com/file/d/1p33nsWQaiZMAgsruDoJLyatoq5XAH-TH/view) and [Prostate](https://drive.google.com/file/d/1-SCjNklFEAq7MlBwcw2ZNR179JqlOubL/view), then unzip and put images in `./dataset/fundus/` and `./dataset/prostate/` in this repo. There are no specific requirments for environment, you can run the code on the latest PyTorch version.

Just unzip? I've tried this but meet errors such as "no such file or directory" when training on Fundus. Maybe I should check dataloader carefully? OK and I'll try again in another environment.
